<!--Autor: @johnsonvieira / https://github.com/johnsonvieira1-->

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">

	<!-- Título -->
	<title>Título do site</title>
	
	<!-- Meta -->
	<meta name="description" content="descrição do seu site">
	<meta name="keywords" content="HTML,CSS">
	<meta name="author" content="Johnson Vieira - @johnsonvieira">

	<!-- Bootstrap -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" media="all">
	
	<!-- Favicon -->
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
	
	<!-- Chamando seu arquivo css -->
	<link rel="stylesheet/less" href="assets/css/style.less" type="text/css">
	
	<!-- Chamando seu script -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.3.1/less.min.js"></script>
	<script href="assets/js/"></script>

</head>
<body>