<!--Autor: @johnsonvieira / https://github.com/johnsonvieira1-->

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">

	<!-- Título -->
	<title>Título do site</title>
	
	<!-- Meta -->
	<meta name="description" content="descrição do seu site">
	<meta name="keywords" content="HTML,CSS">
	<meta name="author" content="Johnson Vieira - @johnsonvieira">
	
	<!-- Favicon -->
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
	
	<!-- Chamando seu arquivo css -->
	<link rel="stylesheet" href="assets/css/style.css">
	
	<!-- Chamando seu script -->
	<script href="assets/js/"></script>

</head>
<body>